[
  {
    "title": "Spicy Bengali Fish Curry",
    "price_min": 250,
    "price_max": 350,
    "email": "order1@stylishfood.com",
    "category": "Seafood",
    "created_at": "2025-11-01T10:00:00Z",
    "image": "https://i.ibb.co.com/mFgMfkr4/machher-jhol-machha-jhola-traditional-spicy-fish-curry-bengali-odia-cuisines-closeup-plate-horizonta.webp",
    "status": "cook",
    "shoplocation": "Dhaka, Bangladesh",
    "onerImg": "https://example.com/owners/owner1.jpg",
    "onerEmail": "owner1@stylishfood.com",
    "description": "A traditional Bengali fish curry prepared with fresh river fish, mustard oil, and a perfect blend of spices. This dish is known for its rich and spicy flavor that warms your soul. Cooked slowly to perfection, it offers an authentic taste of Bengal in every bite. Great to serve with steamed rice. Ideal for fish lovers looking for a spicy delight.",
    "oner_contact": "+8801712345678"
  },
  {
    "title": "Classic Chicken Biryani",
    "price_min": 300,
    "price_max": 450,
    "email": "order2@stylishfood.com",
    "category": "Biryani",
    "created_at": "2025-11-02T12:30:00Z",
    "image": "https://i.ibb.co.com/Xx8hkcjh/crispy-chicken-biryani-served-in-classic-indian-plate-style-biryani-free-photo.jpg",
    "status": "complete",
    "shoplocation": "Chittagong, Bangladesh",
    "onerImg": "https://example.com/owners/owner2.jpg",
    "onerEmail": "owner2@stylishfood.com",
    "description": "Aromatic and flavorful chicken biryani cooked with basmati rice, tender chicken pieces, saffron, and a blend of traditional spices. This biryani is slow-cooked to allow all the flavors to mingle perfectly, delivering a mouthwatering experience. Served with raita and salad, it's a classic choice for festive meals and family gatherings.",
    "oner_contact": "+8801712345679"
  },
  {
    "title": "Veggie Delight Pizza",
    "price_min": 400,
    "price_max": 600,
    "email": "order3@stylishfood.com",
    "category": "Pizza",
    "created_at": "2025-11-03T14:15:00Z",
    "image": "https://i.ibb.co.com/y2Sf25c/istockphoto-842082336-612x612.jpg",
    "status": "cook",
    "shoplocation": "Sylhet, Bangladesh",
    "onerImg": "https://example.com/owners/owner3.jpg",
    "onerEmail": "owner3@stylishfood.com",
    "description": "A delicious veggie pizza topped with fresh tomatoes, capsicum, olives, mushrooms, and mozzarella cheese. Baked on a crispy thin crust with our special tomato sauce, this pizza is perfect for vegetarians and anyone craving a fresh and healthy treat. Ideal for casual meals or parties with friends and family.",
    "oner_contact": "+8801712345680"
  },
  {
    "title": "Beef Steak Special",
    "price_min": 700,
    "price_max": 900,
    "email": "order4@stylishfood.com",
    "category": "Steak",
    "created_at": "2025-11-04T18:00:00Z",
    "image": "https://i.ibb.co.com/j9vHcnpG/istockphoto-1371751060-612x612.jpg",
    "status": "complete",
    "shoplocation": "Khulna, Bangladesh",
    "onerImg": "https://example.com/owners/owner4.jpg",
    "onerEmail": "owner4@stylishfood.com",
    "description": "Juicy and tender beef steak grilled to perfection with a smoky flavor and seasoned with herbs and spices. Served with a side of mashed potatoes and steamed vegetables, this dish is a great choice for meat lovers. Our chef's special marinade ensures every bite is full of richness and satisfaction.",
    "oner_contact": "+8801712345681"
  },
  {
    "title": "Classic Egg Roll",
    "price_min": 80,
    "price_max": 120,
    "email": "order5@stylishfood.com",
    "category": "Fast Food",
    "created_at": "2025-11-05T09:45:00Z",
    "image": "https://i.ibb.co.com/Z1pKGxhh/images.jpg",
    "status": "cook",
    "shoplocation": "Rajshahi, Bangladesh",
    "onerImg": "https://example.com/owners/owner5.jpg",
    "onerEmail": "owner5@stylishfood.com",
    "description": "A popular street food, the classic egg roll is stuffed with fluffy eggs, fresh vegetables, and a blend of spices wrapped in a soft paratha. Perfect for a quick snack or a light meal, it is loved by all age groups and delivers great taste and nutrition.",
    "oner_contact": "+8801712345682"
  },
  {
    "title": "Mango Smoothie Bowl",
    "price_min": 150,
    "price_max": 200,
    "email": "order6@stylishfood.com",
    "category": "Beverages",
    "created_at": "2025-11-06T08:00:00Z",
    "image": "https://i.ibb.co.com/Jw9K3mb9/mango-smoothie-bowl-featured-image.jpg",
    "status": "complete",
    "shoplocation": "Barishal, Bangladesh",
    "onerImg": "https://example.com/owners/owner6.jpg",
    "onerEmail": "owner6@stylishfood.com",
    "description": "A refreshing mango smoothie bowl made with ripe mangoes, yogurt, honey, and topped with granola and fresh fruits. This healthy treat is perfect for breakfast or as a dessert to cool you down during hot days. Rich in vitamins and antioxidants, it supports a balanced diet.",
    "oner_contact": "+8801712345683"
  },
  {
    "title": "Garlic Butter Prawns",
    "price_min": 500,
    "price_max": 700,
    "email": "order7@stylishfood.com",
    "category": "Seafood",
    "created_at": "2025-11-07T19:30:00Z",
    "image": "https://i.ibb.co.com/2096vnk3/images-1.jpg",
    "status": "cook",
    "shoplocation": "Mymensingh, Bangladesh",
    "onerImg": "https://example.com/owners/owner7.jpg",
    "onerEmail": "owner7@stylishfood.com",
    "description": "Delicious prawns sautéed in garlic butter sauce and herbs, served hot and garnished with fresh parsley. This seafood delicacy is a favorite among prawns lovers and pairs well with steamed rice or crusty bread. Made fresh daily using premium quality ingredients.",
    "oner_contact": "+8801712345684"
  },
  {
    "title": "Paneer Tikka Masala",
    "price_min": 350,
    "price_max": 450,
    "email": "order8@stylishfood.com",
    "category": "Vegetarian",
    "created_at": "2025-11-08T15:20:00Z",
    "image": "https://i.ibb.co.com/sJ3CQvrf/0-0-3-2.png",
    "status": "complete",
    "shoplocation": "Comilla, Bangladesh",
    "onerImg": "https://example.com/owners/owner8.jpg",
    "onerEmail": "owner8@stylishfood.com",
    "description": "Soft paneer cubes marinated with spices and grilled to perfection, then cooked in a rich and creamy tomato-based masala sauce. This dish is a popular vegetarian choice packed with flavor and aroma, best enjoyed with naan or rice. Ideal for special occasions and everyday meals.",
    "oner_contact": "+8801712345685"
  },
  {
    "title": "Chocolate Lava Cake",
    "price_min": 180,
    "price_max": 250,
    "email": "order9@stylishfood.com",
    "category": "Dessert",
    "created_at": "2025-11-09T20:45:00Z",
    "image": "https://i.ibb.co.com/8ncG3gt5/276304lava-cake-Kim-e03d3bc55516400e8d05b8d84b524b73.jpg",
    "status": "cook",
    "shoplocation": "Tangail, Bangladesh",
    "onerImg": "https://example.com/owners/owner9.jpg",
    "onerEmail": "owner9@stylishfood.com",
    "description": "A rich and gooey chocolate lava cake with a molten center that oozes out when cut open. Made with premium dark chocolate and fresh eggs, this dessert is a perfect treat for chocolate lovers. Served warm with a scoop of vanilla ice cream, it’s a heavenly indulgence.",
    "oner_contact": "+8801712345686"
  },
  {
    "title": "Falooda Special",
    "price_min": 120,
    "price_max": 160,
    "email": "order10@stylishfood.com",
    "category": "Beverages",
    "created_at": "2025-11-10T17:10:00Z",
    "image": "https://i.ibb.co.com/99XkVLtT/Rose-Falooda-Featured-Image.jpg",
    "status": "complete",
    "shoplocation": "Dinajpur, Bangladesh",
    "onerImg": "https://example.com/owners/owner10.jpg",
    "onerEmail": "owner10@stylishfood.com",
    "description": "A popular traditional dessert drink made with rose syrup, vermicelli, basil seeds, milk, and ice cream. Falooda is refreshing and sweet, perfect for hot summer days or as a dessert after meals. Loved across Bangladesh for its unique taste and cooling effect.",
    "oner_contact": "+8801712345687"
  }
]
